BACKUP DATABASE [COMPANY DATABASE] TO DISK = 'F:\Transfer\XXXXX\COMPANY_DATABASE_TRANSFER_COPY.tmp'  WITH COPY_ONLY, FORMAT
GO
 RESTORE DATABASE [COMPANY_DATABASE_COPY] FROM DISK = 'F:\Transfer\XXXXX\COMPANY_DATABASE_TRANSFER_COPY.tmp'  WITH MOVE 'LOGICAL DATABASE NAME' TO 'F:\Data\COMPANY_DATABASE_TRANSFER_COPY_data.mdf',
 MOVE 'LOGICAL LOG Name' TO 'G:\Log\COMPANY_DATABASE_TRANSFER_COPY_log.ldf' , NOUNLOAD
GO
ALTER DATABASE [COMPANY_DATABASE_COPY] SET ENCRYPTION OFF;
GO
WHILE EXISTS (SELECT encryption_state FROM sys.dm_database_encryption_keys WHERE DB_NAME(database_id)  = 'COMPANY_DATABASE_COPY' AND encryption_state > 1)
BEGIN
	WAITFOR DELAY '00:02';
END
GO
USE [COMPANY_DATABASE_COPY]
GO
DROP DATABASE ENCRYPTION KEY
GO
DECLARE @BackupFileName VARCHAR(1024) = 'F:\Transfer\XXXXX\COMPANY_DATABASE_' + (SELECT CONVERT(varchar, GetDate(), 23)) +'_bak.bak'
BACKUP DATABASE [COMPANY_DATABASE_COPY] TO DISK = @BackupFileName WITH COPY_ONLY, FORMAT
GO
USE master
GO
DROP DATABASE [COMPANY_DATABASE_COPY]
GO
